#!/bin/sh
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/compat/compat.ko
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/net/wireless/cfg80211.ko
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/net/mac80211/mac80211.ko
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/drivers/net/wireless/ti/wlcore/wlcore.ko
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/drivers/net/wireless/ti/wlcore/wlcore_sdio.ko
insmod /lib/modules/3.10.17-1.0.0_ga+g232293e/updates/drivers/net/wireless/ti/wl18xx/wl18xx.ko
